### ISSUE TITLE
[BUG] 引入组件的中间件后，发送一次请求会执行两次

### ISSUE THREAD

**Issue by jobinli** [daodao97/apidog#10]
新创建一个项目，做好数据库配置后，仅仅require了 ```hyperf/db```  与 ```daodao97/apidog``` 组件，做好相应配置，然后启动服务，用curl请求接口一次，发现写入了两条数据，并输出了两次```var_dump``` 
 结果。
![image](https://user-images.githubusercontent.com/59111601/79964888-ea21f200-84bd-11ea-9b13-3c641c824242.png)

具体代码我放在了 https://github.com/jobinli/hyperf-test

**Comment by daodao97** [comment]
不好意思, 最近有点忙, 处理的慢了一些, 反馈的问题已经在 `1.5.1` 版本中得到修复.
具体原因 在 `vendor/daodao97/apidog/src/Middleware/ApiValidationMiddleware.php` 第 `82` , 当没有扫描到注解时, 提前返回 `handle` 中,  忘记 `return` 了

谢谢反馈.
