### ISSUE TITLE
当前支持注解路由吗？

### ISSUE THREAD

**Issue by lai416703504** [daodao97/apidog#18]
swagger是生成是有路由地址的，但是postman请求返回not found、
需要在config/routes.php 添加相同的路由 才可以请求

**Comment by daodao97** [comment]
[src/ConfigProvider.php ](https://github.com/daodao97/apidog/blob/master/src/ConfigProvider.php) line 12 可见
组件会覆写到 RouteDispatch 的实现类
由 [DispatcherFactory.php](https://github.com/daodao97/apidog/blob/master/src/DispatcherFactory.php) 来注册路由

你可以本地进入这个类 dubug 下, 正常是会自动注册路由的.

**Comment by lai416703504** [comment]
我知道我哪里写错了
```php
/**
 * @ApiController(server="http",tag="相关",description="相关控制器",prefix="/aaa/bbb/")
 */
class AaaController
{
    /**
     * @PostApi(path="ccc",description="xxx")
     */
    public function aa(){
         // code
    }
}
```

ApiController 里面的 prefix 后面带了斜杠
