### ISSUE TITLE
怎么写上传文件的注解

### ISSUE THREAD

**Issue by lai416703504** [daodao97/apidog#19]
怎么写上传文件的注解

**Comment by daodao97** [comment]
`file` 类型目前还不支持, 具体支持的注解[doc](https://github.com/daodao97/apidog#%E6%94%AF%E6%8C%81%E7%9A%84%E6%B3%A8%E8%A7%A3)

文件类型的支持只需实现相应`注解`, `swagger 解析`, `参数验证` 即可. 

有兴趣的话可以 `PR`, 后续有空我也会完善.

**Comment by daodao97** [comment]
```php
 /**
     * @FormData(key="file|文件", rule="file")
     */
```
指定 `rule` 为 `file` 即可.
