### ISSUE TITLE
之前的1.6版本呢？现在1.5的consumes有点问题啊

### ISSUE THREAD

**Issue by lai416703504** [daodao97/apidog#21]
之前的1.6版本呢？现在1.5的consumes有点问题啊

**Comment by daodao97** [comment]
版本列表可见这里 [Tags](https://github.com/daodao97/apidog/tags)
上文说的`有点问题`是指什么问题?

**Comment by lai416703504** [comment]
生成的swagger.json 导入到postman的时候出现问题
postman错误信息是这样的
`Error while importing Swagger 2.0: (Patchable) operation.consumes must be an array`

**Comment by lai416703504** [comment]
就是为POST方法的时候生成的swagger.json consumes是个字符串，但是导入postman的时候，需要的是数组

**Comment by daodao97** [comment]
Fixed in [PR](https://github.com/daodao97/apidog/pull/23)
