### ISSUE TITLE
这个api注解支持多server吗，在@ApiController(server="")好像没用啊

### ISSUE THREAD

**Issue by lai416703504** [daodao97/apidog#22]
这个api注解支持多server吗，在@ApiController(server="")好像没用啊

**Comment by daodao97** [comment]
暂时还不支持多server, 可以具体描述下场景需求, 我看下是否可以迭代支持.

**Comment by lai416703504** [comment]
这个我暂时参考 \Hyperf\Apidog\BootAppConfListener写多了一个listener解决了

**Comment by daodao97** [comment]
通用化场景的可以把特性 `PR` 过来, 😁

**Comment by lai416703504** [comment]
我有空的话，搞一搞吧
