### ISSUE TITLE
文档外网访问

### ISSUE THREAD

**Issue by web3coderecho** [daodao97/apidog#35]
UICommand -> handle->host=>127.0.0.1 文档启动外网无法访问 修改为0.0.0.0时 外网能访问 但是文档页面访问的0.0.0.0:9939/swagger.json 需要页面手动将0.0.0.0改成访问地址才能正常访问

**Comment by daodao97** [comment]
已优化 [@commit](https://github.com/daodao97/apidog/commit/05f67562de73bfa38eb9cc90bf46dbb695c444cc)
