### ISSUE TITLE
ApiResponse schema的数据data如何使用list

### ISSUE THREAD

**Issue by MalongGuo** [daodao97/apidog#36]
![image](https://user-images.githubusercontent.com/18382257/95182851-b92d4380-07f7-11eb-86fa-000689b66129.png)

![image](https://user-images.githubusercontent.com/18382257/95182575-65baf580-07f7-11eb-9e7d-bb76ba0bdfd5.png)

ApiReponse的data list 不是显示的userIInfoDetail的definition的值，而是显示的{$refs: "UserInfoDetail"}这个string

**Comment by daodao97** [comment]
目前 `response` 中 `$ref` 的支持仅在第一层, 如文档中[info接口](https://github.com/daodao97/apidog#%E6%A0%B7%E4%BE%8B)
响应体内部深层`key` 为`$ref`暂不支持, 后续会考虑一下是否有必要做深层次的解析.
