### ISSUE TITLE
[bug] 使用 Hyperf 中自定义的验证规则无效

### ISSUE THREAD

**Issue by nfangxu** [daodao97/apidog#37]
[自定义验证规则文档](https://hyperf.wiki/2.0/#/zh-cn/validation?id=%e8%87%aa%e5%ae%9a%e4%b9%89%e9%aa%8c%e8%af%81%e8%a7%84%e5%88%99)

> 通过自定义的方式, 添加了验证规则, 在 Request 中是有效的, 但是在使用了 APIDOG 的时候, 会提示规则不存在

**Comment by daodao97** [comment]
暂时没有支持hyperf的 request rule 的验证, 自定义验证可以参考[文档](https://github.com/daodao97/apidog#%E6%A0%B7%E4%BE%8B)
中的自定义验证

**Comment by nfangxu** [comment]
因为啥呢  技术问题吗  还是 hyperf 的问题  🐶 [狗头保命]

**Comment by daodao97** [comment]
最开始写 [Apidog] 的时候  `hpyerf/validation` 组件还未完善, 目前来看, 上方说的`自定义验证规则`, 是基于`ValidatorFactoryResolved `事件的, 现在 `apidog` 是基于官方验证组件来做的, 理论上会有 `ValidatorFactoryResolved ` 事件, 实际应用中, 执行在业务代码中监听此事件即可.
