### ISSUE TITLE
[BUG]生成的文档没有内容,但接口可以访问

### ISSUE THREAD

**Issue by ZhengSheng1992** [daodao97/apidog#39]
// 当你有多个 http server 时, 可以在输出文件的名称中增加 {server} 字面变量
    // 比如 /public/swagger/swagger_{server}.json

开启多服务时必须配置成 /public/swagger/swagger_{server}.json。每个服务会生成一次wagger.json,如果是/public/swagger/swagger.json,最后一次服务会覆盖掉之前的。

**Comment by daodao97** [comment]
多服务时会按服务构建相关 `swagger` 信息, 输出文件名中必须保留字面变量 `{server}` 用于区分不同服务, 如果去掉, 那么两个服务的信息会写入统一文件(文件写入是覆盖式的)

所以, 如果你有多个服务, 请务必在输出文件的路径中保留 `{server}` 字面量
