### ISSUE TITLE
@ApiController(prefix="/admin" 不起作用

### ISSUE THREAD

**Issue by nirvana72** [daodao97/apidog#42]
@ApiController(prefix="/admin" 不起作用

**Comment by daodao97** [comment]
路由注册中又一处逻辑漏洞, 具体代码见 [DispatcherFactory.php#L44](https://github.com/daodao97/apidog/blob/master/src/DispatcherFactory.php#L44)

暂时可以将 `prefix="/admin"` 改为 `prefix="admin"` 即可.

后续版本提升对是否已 `/` 开头的兼容性.

**Comment by nirvana72** [comment]
![image](https://user-images.githubusercontent.com/15214079/100323385-9f8ec800-3000-11eb-9a4d-be7d784fb490.png)
去掉 / 也没有起作用

**Comment by daodao97** [comment]
请暂时先如下写, 并先清理缓存再启动swaggerUi  `rm -rf runtime/container`
```php

@ApiController(prefix="/admin")

@GetApi(path="captcha")

```
后续版本会兼容各种有无 `/` 开头写法, 不影响现有代码.

**Comment by daodao97** [comment]
统一 `version`, `prefix`, `path` 的前缀处理逻辑 apidog@version  1.5.12

**Comment by nirvana72** [comment]
666
