### ISSUE TITLE
@GetApi(path="auths/{id}/haha")  -- uri中带path参数，生成的路由不正确

### ISSUE THREAD

**Issue by nirvana72** [daodao97/apidog#43]
![image](https://user-images.githubusercontent.com/15214079/100435767-5c545800-30d9-11eb-8875-626c2e4c830a.png)

**Comment by nirvana72** [comment]
![Uploading image.png…]()

**Comment by nirvana72** [comment]
![image](https://user-images.githubusercontent.com/15214079/100437135-46e02d80-30db-11eb-90a0-d1c3beb89bf3.png)

**Comment by daodao97** [comment]
请查看fastRoute文档

**Comment by nirvana72** [comment]
看了fastRoute文档， 配置带path参数URL的方式有几种
$r->addRoute('GET', '/user/{name}', 'handler');
$r->addRoute('GET', '/user/{id:\d+}', 'handler');

但是这个apidog框架不行
写成  * @GetApi(path="auths/{id}")
生成的swagger接口为   xxx/auths{id}  没有斜杠， 手动加斜杠，路由也不存在

写成  * @GetApi(path="auths/{id:\d+}") 
生成的swagger接口为   xxx/auths{id:\d+}  还是斜杠问题

写成  * @GetApi(path="auths//{id}")  写两个斜杠
生成的swagger接口倒是对了， 但path参数取不到

**Comment by daodao97** [comment]
请先升级 apidog 到最新版本.

**Comment by nirvana72** [comment]
我现在的版本是 1.5.13， 之前是1.5.12
现在@GETAPI(path="auths/{id}") 生成的路由正确了
但是 path参数取不到
    $id1 = $this->request->input('id'); // null
    $id2 = $this->request->query('id'); // null
    $id3 = $this->request->path('id');  // string(30) "admin/administrator/auths/1231"
    $all = $this->request->all(); // array(0) {}

应该怎么取path参数呢
