### ISSUE TITLE
使用apidog时为什么我的路由会冲突?

### ISSUE THREAD

**Issue by i-ylsq** [daodao97/apidog#56]
一开始这个问题其实并不严重 但是当我需要使用中间件来通过token 验证用户时 发现了这个问题
`
/**
   * @PostApi(path="/refresh_token", description="刷新token")
   * @ApiResponse(code="200", description="请求成功", schema={
   *   "qid":"5fe97d21bae1a-B129B32C-82F054E3",
   *   "code":200,
   *   "data":{
   *     "token|token":"",
   *     "exp|过期时间": 7200,
   *   },
   *   "msg":"操作成功",
   *   "_": 1609137441
   * })
   */
public function refresh_token(){

}

Router::post('/refresh_token', 'App\Controller\UserController@refreshToken', ['middleware' => $middleware]);
`

代码如上

错误信息:
PHP Fatal error:  Uncaught FastRoute\BadRouteException: Cannot register two routes matching "/refresh_token" for method "POST" in /home/www/apitest.qiduo.net/vendor/nikic/fast-route/src/DataGenerator/RegexBasedAbstract.php:86

**Comment by daodao97** [comment]
两个同名同方法路由 `POST::/refresh_token`  可定要冲突的

**Comment by i-ylsq** [comment]
> 两个同名同方法路由 `POST::/refresh_token` 可定要冲突的
也就是说在使用 apidog 时 默认就是使用注解路由的是吗？  假如是的话 我应该如何在注解路由中引用 jwt 的中间件呢？

**Comment by daodao97** [comment]
`apidog` 的注解和 原生注解并不冲突, 注解下该如何定义中间件, 参见官方文档[通过注解定义中间件](https://hyperf.wiki/2.0/#/zh-cn/middleware/middleware?id=%e9%80%9a%e8%bf%87%e6%b3%a8%e8%a7%a3%e5%ae%9a%e4%b9%89)

**Comment by i-ylsq** [comment]
谢谢 已经解决了
