### ISSUE TITLE
如何验证三个字段中只能有一个字段不为空

### ISSUE THREAD

**Issue by v8oo00** [daodao97/apidog#57]
如何验证三个字段中只能有一个字段不为空谢谢您

**Comment by daodao97** [comment]
目前没有这种 `rule`, 可以从 [lavarel/validation/rule](https://learnku.com/docs/laravel/5.8/validation/3899#5d21f1) 中找找, 看是否有符合你需求的

另外: 这个场景感觉比较奇怪, 统一成一个key, 类型 enum 应该会更合理些

**Comment by v8oo00** [comment]
非常感谢！


| |
王栋梁
|
|
marsked@163.com
|
签名由网易邮箱大师定制


在2020年12月31日 18:13，刀刀<notifications@github.com> 写道：

目前没有这种 rule, 可以从 lavarel/validation/rule 中找找, 看是否有符合你需求的

另外: 这个场景感觉比较奇怪, 统一成一个key, 类型 enum 应该会更合理些
