### ISSUE TITLE
怎么自定义验证规则？

### ISSUE THREAD

**Issue by ZhengSheng1992** [daodao97/apidog#59]
根据hyper文档写得自定义验证规则添加,识别不了
BadMethodCallException:Method Hyperf\Validation\Validator::validateFoo does not exist.(236) in /www/wwwroot/hyperf/vendor/hyperf/validation/src/Validator.php

**Comment by ZhengSheng1992** [comment]
$validator = $this->validationFactory->make(
            $param,
            [
                'amount' => 'required|foo',
            ],
            [
                'amount.required' => '请输入数量',
                'amount.foo' => '格式不正确',
            ]
        );

        if ($validator->fails()){
            // Handle exception
            $errorMessage = $validator->errors()->first();

            var_dump($errorMessage);
        }
这样验证是可以的 注解就不行

**Comment by ZhengSheng1992** [comment]
Validation.php
    public function __construct()
    {
        $this->container = ApplicationContext::getContainer();
        $this->factory = $this->container->get(ValidatorFactory::class);
        $this->customValidateRules = $this->container->get(ValidationCustomRule::class);
    }
改成
    public function __construct()
    {
        $this->container = ApplicationContext::getContainer();
        $this->factory = $this->container->get(ValidatorFactoryInterface::class);
        $this->customValidateRules = $this->container->get(ValidationCustomRule::class);
    }
即可

**Comment by daodao97** [comment]
`apidog` 封装了内部校验逻辑, 不支持 `hyperf` 原生的自定义校验, 
![image](https://user-images.githubusercontent.com/15009280/105146867-66c02a80-5b3b-11eb-8afa-8f35e17cc27d.png)
如上图是`控制器回调校验` 的方式, 当然也支持更丰富的校验方式, 可以基于 [ValidationCustomRule](https://github.com/daodao97/apidog/blob/master/src/Validation/ValidationCustomRule.php) 扩展自己的校验规则.

原则上, 简单的, 一次性的校验使用`控制器回调` 的方式, 通用的, 可复用的 使用  `扩展 ValidationCustomRule` 的方式
