### ISSUE TITLE
你好，发现一个bug，多个server，swagger.json写入失败

### ISSUE THREAD

**Issue by jhansin-zhang** [daodao97/apidog#60]
![image](https://user-images.githubusercontent.com/52953730/113467000-b6dc3700-9472-11eb-8a2c-250634ba73d2.png)
![image](https://user-images.githubusercontent.com/52953730/113467002-bf347200-9472-11eb-9240-887d0e9b2986.png)
当存在一个server时，swagger.json写入正常， 当存在多个swagger.json时，写入失败

**Comment by jhansin-zhang** [comment]
![image](https://user-images.githubusercontent.com/52953730/113467293-b17fec00-9474-11eb-97a5-2e014d929da4.png)

这样修改就正常了

**Comment by daodao97** [comment]
多服务时确保`output` 中有 `{server}` 字面变量, 例如`output_file: /public/swagger/swagger_{server}.json` [code](https://github.com/daodao97/apidog/blob/master/publish/apidog.php#L17)
