### ISSUE TITLE
全局参数能否设置 比如 签名

### ISSUE THREAD

**Issue by yangtze64** [daodao97/apidog#61]

**Comment by daodao97** [comment]
目前不支持, 可以添加此特性, 得空了搞一下

**Comment by four-li** [comment]
+1  ，一般都有这样从请求中 header 添加 'X-TOKEN'  😄

**Comment by daodao97** [comment]
已提交到 master 分支, [commit](https://github.com/daodao97/apidog/commit/fd3cc8c255beec1d7814c3232711c0937c0b7e5d)
可以先试试, 待我测试完全后发版.

**Comment by daodao97** [comment]
在 `1.15.16` 版本中发布
