### ISSUE TITLE
无法更新swagger.json

### ISSUE THREAD

**Issue by zhengzhishanliang** [daodao97/apidog#64]
环境：php7.4，hyperf 2.0.11 ，daodao97/apidog 1.5.17

按照部署文档：

# 1、有多个servers ,在apidog.php配置了
![1640167224(1)](https://user-images.githubusercontent.com/50315515/147075503-43582b9b-394e-4920-9713-6e407f41ce04.png)

# 2、整个项目的注解就只用了部署文档的DemoController:
![1640167363(1)](https://user-images.githubusercontent.com/50315515/147074764-3d132802-955d-431e-86c7-6539d92d21e3.png)
### 顺便提一句：DemoController 没有引用完全，缺失
- use Hyperf\Apidog\Annotation\ApiDefinitions;
- use Hyperf\Apidog\Annotation\ApiDefinition;

# 3、php bin/hyperf.php start 时，有生成 swagger_http.json文件，但无更多内容（路由，参数等信息）
![1640167474(1)](https://user-images.githubusercontent.com/50315515/147075391-ebb8c6d6-c752-4f76-afe5-f2b927960c2b.png)

请问这是为什么，谢谢！

**Comment by daodao97** [comment]
多服务时需在api中指定当前接口输入到那个服务, 请参考文档 `@ApiServer(name="http")` 部分

**Comment by zhengzhishanliang** [comment]
感谢，确实是这个问题，再次表示感谢！
