### ISSUE TITLE
当路由文件与注解指向同一个方法时候，路由解析错误

### ISSUE THREAD

**Issue by jobinli** [daodao97/apidog#7]
![image](https://user-images.githubusercontent.com/59111601/78764235-d902bc80-79b8-11ea-81a7-0ed36b84bc8d.png)
此时解析出来的controller为A。
在routers.php
```php
Router::addRoute(['GET', 'POST', 'HEAD'], '/', 'App\Controller\IndexController@index');
```
同时在```App\Controler\IndexController@index```中用了例子中的注解
![image](https://user-images.githubusercontent.com/59111601/78764102-a789f100-79b8-11ea-99ea-8a03095e8970.png)

虽然这是一个不应该出现的错误用法。

**Comment by daodao97** [comment]
当前版本比较激进, 在注解方式和手动注册方式中选择了 `注解方式` 这种, 也就是系统只能用注解方式注册路由,  将会在下个版本同时支持两种情况, 做到更为兼容.

**Comment by daodao97** [comment]
最新版本已经做了兼容.
